'use strict';
const gcd=(a,b)=>{a=a<0n?-a:a;b=b<0n?-b:b;while(b){[a,b]=[b,a%b]}return a||1n};
function Q(n,d=1n){if(d===0n)throw Error('Singular basis: P has no inverse.');if(d<0n){n=-n;d=-d}const g=gcd(n,d);return [n/g,d/g]}
function read(s){s=s.trim();if(s.length>40)throw Error('Input exceeds the rational budget.');if(/^-?\d+\/\d+$/.test(s)){const [n,d]=s.split('/');return Q(BigInt(n),BigInt(d))}if(!/^-?\d+(\.\d+)?$/.test(s))throw Error('Enter an integer, decimal or fraction.');const sign=s.startsWith('-')?-1n:1n;s=s.replace('-','');const [a,b='']=s.split('.');return Q(sign*BigInt(a+b),10n**BigInt(b.length))}
const add=(a,b)=>Q(a[0]*b[1]+b[0]*a[1],a[1]*b[1]);const neg=a=>[-a[0],a[1]];const sub=(a,b)=>add(a,neg(b));const times=(a,b)=>Q(a[0]*b[0],a[1]*b[1]);const divide=(a,b)=>Q(a[0]*b[1],a[1]*b[0]);const f=a=>a[1]===1n?String(a[0]):a.join('/');const num=a=>Number(a[0])/Number(a[1]);const zero=Q(0n);
const determinant=a=>sub(times(a[0][0],a[1][1]),times(a[0][1],a[1][0]));
function inverse(a){const d=determinant(a);return [[divide(a[1][1],d),divide(neg(a[0][1]),d)],[divide(neg(a[1][0]),d),divide(a[0][0],d)]]}
const mult=(a,b)=>a.map((row,i)=>b[0].map((_,j)=>add(times(row[0],b[0][j]),times(row[1],b[1][j]))));
const apply=(a,v)=>a.map(row=>add(times(row[0],v[0]),times(row[1],v[1])));
const format=a=>a.map(row=>'[ '+row.map(f).join('   ')+' ]').join('\n');
function compute(p,a){const pi=inverse(p),v=[Q(2n),Q(1n)],q=apply(pi,v),b=mult(mult(pi,a),p);return {p,a,v,q,b,av:apply(a,v),naive:apply(p,apply(a,q)),trace:add(a[0][0],a[1][1]),det:determinant(a),rank:determinant(a)[0]!==0n?2:a.flat().some(v=>v[0]!==0n)?1:0}}
if(typeof module!=='undefined')module.exports={read,Q,compute,f,apply,mult,inverse};
if(typeof document!=='undefined'){
 const matrix=id=>{const a=[...document.querySelectorAll('#'+id+' input')].map(i=>read(i.value));return [a.slice(0,2),a.slice(2)]};let current;
 function draw(d){const svg=document.getElementById('plot');const vectors=[d.v,d.av,[d.p[0][0],d.p[1][0]],[d.p[0][1],d.p[1][1]]].map(v=>v.map(num));const extent=Math.max(3,...vectors.flat().map(Math.abs))*1.25;const scale=125/extent;const pt=v=>[240+v[0]*scale,165-v[1]*scale];let out='<line x1="25" y1="165" x2="455" y2="165" stroke="var(--line)"/><line x1="240" y1="20" x2="240" y2="310" stroke="var(--line)"/>';
 vectors.forEach((v,i)=>{const [x,y]=pt(v);out+=`<line x1="240" y1="165" x2="${x}" y2="${y}" stroke="${i===0?'var(--accent)':'var(--ink)'}" stroke-width="${i<2?3:1}" ${i>=2?'stroke-dasharray="5 4"':''}/><circle cx="${x}" cy="${y}" r="4" fill="${i===0?'var(--accent)':'var(--ink)'}"/><text x="${x+7}" y="${y-7}" fill="var(--ink)">${['v','Av','b₁','b₂'][i]}</text>`});out+='<text x="430" y="187" fill="var(--muted)">x (m)</text><text x="250" y="28" fill="var(--muted)">y (m)</text>';svg.innerHTML=out;
 }
 function update(){try{current=compute(matrix('basis'),matrix('operator'));document.getElementById('error').textContent='';const status=document.getElementById('status');status.className='';status.textContent='VERIFIED · exact object and operator equivalence';draw(current);const d=current;document.getElementById('values').textContent='[v]A = ('+d.v.map(f).join(', ')+')\n[v]B = ('+d.q.map(f).join(', ')+')\n\nB = P⁻¹AP\n'+format(d.b)+'\n\nCorrect transformed object = ('+d.av.map(f).join(', ')+')\nUnchanged A in new coordinates gives ('+d.naive.map(f).join(', ')+')';document.getElementById('invariants').innerHTML=`<tr><td>Trace</td><td>${f(d.trace)}</td></tr><tr><td>Determinant</td><td>${f(d.det)}</td></tr><tr><td>Rank</td><td>${d.rank}</td></tr><tr><td>Characteristic polynomial</td><td>λ² − (${f(d.trace)})λ + (${f(d.det)})</td></tr>`;document.getElementById('prediction-result').textContent='';}catch(e){current=null;const status=document.getElementById('status');status.className='bad';status.textContent='REFUSED · representation is unavailable';document.getElementById('error').textContent=e.message;document.getElementById('plot').innerHTML='';document.getElementById('values').textContent='';document.getElementById('invariants').innerHTML='';document.getElementById('prediction-result').textContent='';}}
 document.querySelectorAll('.matrix input').forEach(i=>i.addEventListener('input',update));document.getElementById('preset').addEventListener('change',e=>{const choices={shear:['1','1','0','1'],rotate:['0','-1','1','0'],scale:['2','0','0','3'],singular:['1','2','2','4']};[...document.querySelectorAll('#basis input')].forEach((i,n)=>i.value=choices[e.target.value][n]);update()});document.getElementById('predict').addEventListener('click',()=>{try{if(!current)throw Error('Choose an invertible basis first.');const a=document.getElementById('prediction').value.split(',').map(read);document.getElementById('prediction-result').textContent=a.length===2&&a.every((v,i)=>f(v)===f(current.q[i]))?'Correct: the coordinates changed and the object stayed fixed.':'Counterexample: compare your prediction with P⁻¹v above.'}catch(e){document.getElementById('prediction-result').textContent=e.message}});update();
}
